#!/bin/bash
cd /home/crawler

git fetch
changed_files="$(git diff -r --name-only master origin/master | grep 'modules/')"
git pull

if [ ${#changed_files} -eq 0 ]
then
    gulp default
else
    gulp default
    systemctl restart crawlerd
fi